#     {push}
#       |
#       v
#    [RUNNER]
#       |
# se connecte à
#       |
#       v
# [INSTANCE AWS]
#       |
#  Build,lance
#       |
#       v
#    [DOCKER]
#
name: deploying
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ secrets.SSH_KEY }}' > ./standard.pem
      - run: chmod 600 ./standard.pem
      - run: ssh -o StrictHostKeyChecking=no admin@${{ secrets.VM_ADDRESS }} -i "./standard.pem" \
            "#nous sommes dans l'instance AWS
             server_script() {
                 #mettre a jour l'image docker
                 #build
                 #relancer
             };
             server_script"