name: deploying
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.SSH_KEY }}" > ./standard.pem
      - run: ssh admin@${{ secrets.VM_ADDRESS }} -i "./standard.pem" -T
     # - run: yes
      - run: cd ./devops && git pull && cd ./with-cypress-app && pm2 reload all